### ISSUE TITLE
npx react-native run-android fails

### ISSUE THREAD

**Issue by dito** [WalletConnect/walletconnect-monorepo#1252]
**Describe the bug**

`yarn run android` and build failed.

I did this setup
https://reactnative.dev/docs/environment-setup

```
yarn add rn-nodeify
./node_modules/.bin/rn-nodeify --install --hack
```

I commited this.
https://github.com/dito/WalletConnectSample

**To Reproduce**

```
❯ yarn run android
yarn run v1.22.15
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 970 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
6 actionable tasks: 6 up-to-date

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ito.daisuke/WalletConnectSample/node_modules/react-native-os/android/build.gradle' line: 47

* What went wrong:
A problem occurred evaluating project ':react-native-os'.
> Could not find method compile() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ito.daisuke/WalletConnectSample/node_modules/react-native-os/android/build.gradle' line: 47

* What went wrong:
A problem occurred evaluating project ':react-native-os'.
> Could not find method compile() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at makeError (/Users/ito.daisuke/WalletConnectSample/node_modules/execa/index.js:174:9)
    at /Users/ito.daisuke/WalletConnectSample/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/ito.daisuke/WalletConnectSample/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/ito.daisuke/WalletConnectSample/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Desktop (please complete the following information):**
 - OS: M1 Mac

**Comment by dito** [comment]
I patched incompatible modules.

**Comment by Sotatek-TuongNguyen** [comment]
@dito same error. What did you do?
