### ISSUE TITLE
Error: Missing or invalid. pair() uri: undefined

### ISSUE THREAD

**Issue by Jake-Mulhern** [WalletConnect/walletconnect-monorepo#1881]
I have set up WalletConnect inside of my React-Native project according to the documentation.  However, when I get to the step where I pair with the dApp using the URI I consistently get the same error:

```
Error: Missing or invalid. pair() uri: undefined
```

Here is my code:
```
          const currentURI = props.route?.params?.walletConnectURI;
          console.log('checking current URI is there: ', currentURI);

          const core = new Core({
            projectId: CONNECT_WALLET_PROJECT_ID
          });

          const web3wallet = await Web3Wallet.init({
            core,
            metadata: {
              name: 'Connect Wallet',
              description: 'A Wallet Application',
              url: "#",
              icons: []
            },
          });

          web3wallet.on("session_proposal", async (proposal) => {
            // const session = await web3wallet.approveSession({
            //   id: proposal.id,
              
            // })
            console.log('wc proposal: ', proposal);
          });
          await web3wallet.core.pairing.pair({ currentURI });
```

The console.log() to check to make sure I am actually passing in the currentURI displays the correct URI passed in from the QR code that I scanned.  I am not sure why it says the URI is undefined.  I've checked it a number of times and also tried passing it in like so:

```
 await web3wallet.core.pairing.pair(currentURI);
```

and even tried hardcoding it in:
```
 await web3wallet.core.pairing.pair("wc:e9999361-c2f9-4814-9a07-1172ebe92141@1?bridge=https%3A%2F%2Fe.bridge.walletconnect.org&key=3e3d41ed85ff7879ec2951a916affe3eee6c4923e3e7e9f7196df0e3e4ee9f1e");
```

```
 await web3wallet.core.pairing.pair({ "wc:e9999361-c2f9-4814-9a07-1172ebe92141@1?bridge=https%3A%2F%2Fe.bridge.walletconnect.org&key=3e3d41ed85ff7879ec2951a916affe3eee6c4923e3e7e9f7196df0e3e4ee9f1e" });
```

Any help in figuring this out would be great.

**Comment by Jake-Mulhern** [comment]
If I switch it to web3wallet.core.pairing.pair({ uri: currentURI }) I get the following error:

```
Object {
  "context": "core",
}, Object {
  "context": "core/relayer",
}, Object {
  "context": "core/relayer/subscription",
}, [Error: Relay Protocol not supported: undefined]
at node_modules/pino/browser.js:164:11 in <global>
at node_modules/@walletconnect/core/dist/index.cjs.js:1:23105 in <global>

[Unhandled promise rejection: Error: Relay Protocol not supported: undefined]
at node_modules/@walletconnect/utils/dist/index.cjs.js:1:7405 in J
at node_modules/@walletconnect/core/dist/index.cjs.js:1:25776 in We#unsubscribeById
at node_modules/@walletconnect/core/dist/index.cjs.js:1:22994 in Y
at node_modules/@walletconnect/core/dist/index.cjs.js:1:31380 in et#get__connected
at node_modules/@walletconnect/core/dist/index.cjs.js:1:31379 in et#get__context
at node_modules/@walletconnect/core/dist/index.cjs.js:1:38278 in create
```

**Comment by Jake-Mulhern** [comment]
Here are the versions of all of the WalletConnect packages:
```
"@walletconnect/auth-client": "^2.0.2",
"@walletconnect/react-native-compat": "^2.2.1",
"@walletconnect/sign-client": "^2.2.1",
"@walletconnect/web3wallet": "^1.0.0",
```

**Comment by ganchoradkov** [comment]
Hey @Jake-Mulhern, the `core.pairing.pair()` method expects as an argument an object with property ` { uri }` so the correct way to pair is to call `core.pairing.pair({ uri: currentURI })` as you did in your second comment :100: 
The error regarding missing `relay Protocol not supported: undefined` is because you're trying to pair v1 dapp with v2 wallet which is not possible as v1 & v2 are incompatible.

Please try out our example dapp that supports v2 and will generate the correct pairing URI
https://react-app.walletconnect.com/
