### ISSUE TITLE
connector from useWalletConnect is not working.

### ISSUE THREAD

**Issue by kormocicsaba** [WalletConnect/walletconnect-monorepo#2071]
Hi!

When i try to use `connector.killSession()` from `const connector = useWalletConnect();` this is the error i got:

How to fix this?
```
Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not a function
TypeError: undefined is not a function
    at getRandomBase64 (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:101337:65)
    at getRandomValues (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:101354:33)
    at randomBytes (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:127164:31)
    at randomBytes (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:127069:43)
    at ?anon_0_ (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:126967:37)
    at next (native)
    at asyncGeneratorStep (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4641:26)
    at _next (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4660:29)
    at anonymous (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4665:14)
    at tryCallTwo (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4657:25)
    at apply (native)
    at generateKey (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:126962:30)
    at ?anon_0_ (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:126998:59)
    at next (native)
    at asyncGeneratorStep (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4641:26)
    at _next (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4660:29)
    at anonymous (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4665:14)
    at tryCallTwo (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4657:25)
    at apply (native)
    at encrypt (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:126993:26)
    at ?anon_0_ (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:120063:55)
    at next (native)
    at asyncGeneratorStep (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4641:26)
    at _next (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4660:29)
    at anonymous (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4665:14)
    at tryCallTwo (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4657:25)
    at apply (native)
    at _encrypt (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:120069:33)
    at ?anon_0_ (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:119684:54)
    at next (native)
    at asyncGeneratorStep (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4641:26)
    at _next (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4660:29)
    at anonymous (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4665:14)
    at tryCallTwo (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4657:25)
    at apply (native)
    at _sendRequest (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:119691:37)
    at ?anon_0_ (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:119469:34)
    at next (native)
    at asyncGeneratorStep (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4641:26)
    at _next (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4660:29)
    at anonymous (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4665:14)
    at tryCallTwo (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/kudo/01_Work/Repos/expo/expo/android/versioned-react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/5a4n485h/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:4657:25)
    at apply (native)
    at killSession (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:119473:36)
    at disconnect (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:179641:30)
    at onPress (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:179442:27)
    at _performTransitionSideEffects (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:62231:22)
    at _receiveSignal (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:62187:45)
    at onResponderRelease (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:62054:34)
    at apply (native)
    at invokeGuardedCallbackProd (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:62639:21)
    at apply (native)
    at invokeGuardedCallback (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:62725:42)
    at apply (native)
    at invokeGuardedCallbackAndCatchFirstError (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:62728:36)
    at executeDispatch (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:62792:48)
    at executeDispatchesInOrder (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:62809:26)
    at executeDispatchesAndRelease (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:63915:35)
    at executeDispatchesAndReleaseTopLevel (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:63922:43)
    at forEach (native)
    at forEachAccumulated (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:63251:22)
    at runEventsInBatch (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:63933:27)
    at runExtractedPluginEventsInBatch (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:63992:25)
    at anonymous (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:63973:42)
    at batchedUpdates$1 (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:74563:20)
    at batchedUpdates (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:63904:36)
    at _receiveRootNodeIDEvent (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:63972:23)
    at receiveTouches (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:64015:34)
    at apply (native)
    at __callFunction (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:2826:36)
    at anonymous (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:2587:31)
    at __guard (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:2777:15)
    at callFunctionReturnFlushedQueue (http://192.168.1.180:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&hot=false:2586:21)
```

**Comment by ganchoradkov** [comment]
hey @Csaba000, could you give more context and code snippets on how you're using our SDK?
I'm seeing that is react-native but which version?
We have a few react-native example apps that you could follow as a reference
https://github.com/WalletConnect/react-native-examples

**Comment by kormocicsaba** [comment]
> hey @Csaba000, could you give more context and code snippets on how you're using our SDK? I'm seeing that is react-native but which version? We have a few react-native example apps that you could follow as a reference https://github.com/WalletConnect/react-native-examples

Yeah, i'm using this library:
https://www.npmjs.com/package/@walletconnect/react-native-dapp

It is possible that this will be updated to support the new v2 version?

**Comment by ganchoradkov** [comment]
Hey @Csaba000, we already have few examples with react-native on v2
https://github.com/WalletConnect/react-native-examples
