### ISSUE TITLE
Web socket connection failed 

### ISSUE THREAD

**Issue by arbaz-meo** [WalletConnect/walletconnect-monorepo#2207]
**Issue**
 i m using the sign client and  i implemented this on server side . 24 hours i not see any issue  of web socket but after 24 hours later i see everyday websocket connection failed . 

**Version  **
 - Sign Client: 2.5.1

**Error Log **

const error = this.parseError(new Error((errorEvent === null || errorEvent === void 0 ? void 0 : errorEvent.message) || `WebSocket connection failed for URL: ${this.url}`));
                                      ^

Error: getaddrinfo EAI_AGAIN relay.walletconnect.com
    at WsConnection.emitError (/home/mywhoosh/apps/Mywhoosh/node_modules/@walletconnect/jsonrpc-ws-connection/dist/cjs/ws.js:160:39)
    at WebSocket.<anonymous> (/home/mywhoosh/apps/Mywhoosh/node_modules/@walletconnect/jsonrpc-ws-connection/dist/cjs/ws.js:118:33)
    at WebSocket.emit (node:events:513:28)
    at emitErrorAndClose (/home/mywhoosh/apps/Mywhoosh/node_modules/ws/lib/websocket.js:895:13)
    at ClientRequest.<anonymous> (/home/mywhoosh/apps/Mywhoosh/node_modules/ws/lib/websocket.js:752:5)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)

    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by ganchoradkov** [comment]
Hey @arbaz-meo, the reason your socket is disconnecting is that the JWT token has 24h expiry. 
After the disconnect, the socket should reconnect automatically. 
Is that not the case?

**Comment by arbaz-meo** [comment]
@ganchoradkov its not connecting automatically . its just throws error

**Comment by arbaz-meo** [comment]
@ganchoradkov @julien51  can you help me to resolve the issue ???

**Comment by arbaz-meo** [comment]
i updated with sign client 2.7.3 error change but still exist with **closeTransport called before connection was established**

**Comment by arbaz-meo** [comment]
@bkrem  i m waiting to hear back on this issue ???

**Comment by finessevanes** [comment]
@arbaz-meo can you try upgrading to the latest: 2.7.7?

**Comment by arbaz-meo** [comment]
@finessevanes its working fine with 2.7.7 .  also thanks to wallet connect team to solving this issue .
