### ISSUE TITLE
WebSocket is not defined using node.js

### ISSUE THREAD

**Issue by Jose1384** [WalletConnect/walletconnect-monorepo#229]
Hi,

Trying to use library "@walletconnect/node" i recieve the next error message:  **ReferenceError: WebSocket is not defined**
```
ReferenceError: WebSocket is not defined
    at Object.t.exports.e (/home/maquina2/Documents/seshat-api/node_modules/@walletconnect/node/lib/index.js:23:61851)
    at r (/home/maquina2/Documents/seshat-api/node_modules/@walletconnect/node/lib/index.js:1:418)
    at function.Object.create.t.exports.t.super_ (/home/maquina2/Documents/seshat-api/node_modules/@walletconnect/node/lib/index.js:1:1217)
    at /home/maquina2/Documents/seshat-api/node_modules/@walletconnect/node/lib/index.js:1:1227
    at e (/home/maquina2/Documents/seshat-api/node_modules/@walletconnect/node/lib/index.js:1:143)
    at Object.<anonymous> (/home/maquina2/Documents/seshat-api/node_modules/@walletconnect/node/lib/index.js:1:285)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
```

I was following the Quick start tutorial(https://docs.walletconnect.org/quick-start/dapps/node). These are only lines i have changed to use node.js framework:

> import NodeWalletConnect from "@walletconnect/browser";
> import WalletConnectQRCodeModal from "@walletconnect/qrcode-modal";

_Imports changed to requires._

> const NodeWalletConnect = require('@walletconnect/node');
> const  WalletConnectQRCodeModal = require("@walletconnect/qrcode-modal");

**Also i have installed 'ws' package.**

Any ideas?

Thanks!.

**Comment by pedrouid** [comment]
My bad, need to look into this in more detail.

> const NodeWalletConnect = require('@walletconnect/node');
> const WalletConnectQRCodeModal = require("@walletconnect/qrcode-modal");

Agreed, these should be better documented

> Also i have installed 'ws' package.

Assign the WebSocket to global scope before instantiating the NodeWalletConnect class
```js
WebSocket = require('ws')

const walletConnector = new NodeWalletConnect(
    // options
)
```

**Comment by pedrouid** [comment]
Hey @Jose1384, could you test the version available on the `next` tag on NPM. It should work without assigning WebSocket to the global scope

```sh
npm install --save @walletconnect/node@next

# OR

yarn add @walletconnect/node@next
```

Let me know how it goes

**Comment by Jose1384** [comment]
> Hey @Jose1384, could you test the version available on the `next` tag on NPM. It should work without assigning WebSocket to the global scope
> 
> ```shell
> npm install --save @walletconnect/node@next
> 
> # OR
> 
> yarn add @walletconnect/node@next
> ```
> 
> Let me know how it goes

Hi @pedrouid , it works fine! :+1: .
