### ISSUE TITLE
[Bug] samples.dapp always crash when it call pushRequest.

### ISSUE THREAD

**Issue by ghost** [WalletConnect/walletconnect-monorepo#2717]
**Describe the bug**
I'm running examples of this repo: `samples.dapp` and `sample.wallet`. 
I've added google-services.json and done paring them successfully as in the picture below. 
Then I tap the Push request button, the app immediately crashes below: 

```
FATAL EXCEPTION: main
Process: com.walletconnect.sample.dapp, PID: 9212
 java.util.NoSuchElementException: Collection contains no element matching the predicate.
at com.walletconnect.sample.dapp.ui.routes.composable_routes.session.SessionViewModel.pushRequest(SessionViewModel.kt:173)
at com.walletconnect.sample.dapp.ui.routes.composable_routes.session.SessionRouteKt$SessionRoute$6.invoke(SessionRoute.kt:76)
at com.walletconnect.sample.dapp.ui.routes.composable_routes.session.SessionRouteKt$SessionRoute$6.invoke(SessionRoute.kt:76)
at com.walletconnect.sample_common.ui.commons.ButtonsKt$BlueButton$1$1.invoke(Buttons.kt:27)
at com.walletconnect.sample_common.ui.commons.ButtonsKt$BlueButton$1$1.invoke(Buttons.kt:26)
at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke-k-4lQ0M(Clickable.kt:167)
at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$1$2.invoke(Clickable.kt:156)
at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:255)
```
I've checked and found out that SignClient.getListOfActiveSessions() always be empty.
Please help to check. Did I miss any config?

**SDK Version (if relevant)**
 - Client: [e.g. JS, Swift, Kotlin]

**To Reproduce**
1. Run samples.dapp and sample.wallet 
2. Connect(pair) dapp with wallet 
3. Pair successfully then click to Request push button
4. See the error

**Expected behavior**
Send Request push to the wallet to approve. Then Dapp can Notify to Wallet

**Screenshots**
![image](https://github.com/WalletConnect/walletconnect-monorepo/assets/43597747/b26646f8-a2cf-4d74-b9ea-7e5c9aa4c021)

**Additional context**

**Comment by ghost** [comment]
That's my mistake. I've log in wrong repo
