### ISSUE TITLE
@walletconnect/truffle-provider@1.3.1 this.updateState is not a function

### ISSUE THREAD

**Issue by jacksonng77** [WalletConnect/walletconnect-monorepo#372]
Receiving the following error using walletconnect with Truffle-provider@1.3.1.

```
RuntimeError: abort(TypeError: this.updateState is not a function). Build with -s ASSERTIONS=1 for more info.
    at process.abort (C:\Users\jacks\.config\truffle\compilers\node_modules\soljson-v0.6.4+commit.1dca32f3.js:1:14444)
    at process.emit (events.js:182:13)
    at process.emit (C:\Users\jacks\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\source-map-support\source-map-support.js:485:1)
    at emitPromiseRejectionWarnings (internal/process/promises.js:119:20)
    at process.internalTickCallback (internal/process/next_tick.js:78:34)
```

My Truffle Config is as follows:

```
require('dotenv').config();
const WalletConnectProvider = require('@walletconnect/truffle-provider').default

let provider = new WalletConnectProvider({
    rpcUrl: `https://ropsten.infura.io/v3/${process.env.INFURA_API_KEY}`
})

module.exports = {
  networks: {
    development: {
      host: "127.0.0.1",     
      port: 7545,            
      network_id: "*",
    },
    ropsten: {
      provider: () => provider,
      network_id: '3',
      networkCheckTimeout: 10000
    },
  },
  compilers: {
    solc: {
      version: "0.6.4+commit.1dca32f3",
      parser: "solcjs",
      settings: {
        optimizer: {
          enabled: true,
          runs: 1   // Optimize for how many times you intend to run the code
        },
        evmVersion: "istanbul"
      }
    }
  },
  plugins: [
    'truffle-contract-size'
  ]
}
```

I ran the command to deploy on Ropsten. 

`truffle migrate --network ropsten`

The deployment begins and my contracts are compiled. The QR code pops up and I attempt to scan it with MetaMask mobile. The scanning was successful and I confirm that I will execute this transaction. 

This is when this error pops up:

`this.updateState is not a function`

Any help is well appreciated. Thank you!

**Comment by piske-alex** [comment]
I commented out the lines with this.updateState and this.emit inside index.js in dist folder and it worked fine

**Comment by miohtama** [comment]
Can you see if the downgrade workaround mentioned here works

https://github.com/ethereum/web3.js/issues/3790

**Comment by snollygolly** [comment]
@miohtama I manually downgraded via `npm install --save web3@1.2.11` and reran my migration with the same error.

**Comment by finessevanes** [comment]
@snollygolly are you still experiencing the issue?
