### ISSUE TITLE
Unable to get my test to be passed: @walletconnect/etherum-provider

### ISSUE THREAD

**Issue by sk-enya** [WalletConnect/walletconnect-monorepo#3838]
**Describe the bug**
After migrating to walletconnect v2 we are able to run the application it's working correctly but causing test cases to failing.

```bash
test: "react-scripts test --watchAll=false"
```

```
 FAIL  src/containers/history/tests/history.test.tsx
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'base16')

      15 | limitations under the License. */
      16 |
    > 17 | import {EthereumProvider} from '@walletconnect/ethereum-provider'
         | ^
      18 | import {providers,utils} from "ethers"
      19 |
      20 | import {setBaseState,setEnableAccount} from 'actions/setupAction'

      at Object.<anonymous> (node_modules/uint8arrays/cjs/src/util/bases.js:42:21)
      at Object.<anonymous> (node_modules/uint8arrays/cjs/src/from-string.js:5:13)
      at Object.<anonymous> (node_modules/uint8arrays/cjs/src/index.js:8:18)
      at Object.<anonymous> (node_modules/@walletconnect/utils/dist/index.cjs.js:1:324)
      at Object.<anonymous> (node_modules/@walletconnect/ethereum-provider/dist/index.cjs.js:1:177)
      at Object.<anonymous> (src/services/wallet.service.js:17:1)
      at Object.<anonymous> (src/services/networkService.js:86:1)
      at Object.<anonymous> (src/components/global/addToMetamask/index.tsx:4:1)
      at Object.<anonymous> (src/components/global/index.ts:1:1)
      at Object.<anonymous> (src/containers/history/History.tsx:23:1)
      at Object.<anonymous> (src/containers/history/tests/history.test.tsx:6:1)

```

**Comment by sk-enya** [comment]
Anyways, I get this working by creating mocks on modules as it's and mapping with jest configuration below.

```json
"jest": {
   "moduleNameMapper": {
      "@walletconnect/ethereum-provider": "<rootDir>/__mocks__/@walletconnect/ethereum-provider.ts"
    },
}
```

**Comment by sk-enya** [comment]
Closing issue now! thanks..
