### ISSUE TITLE
"Writable" is not exported by "__vite-browser-external"

### ISSUE THREAD

**Issue by peterpeterparker** [WalletConnect/walletconnect-monorepo#4414]
**Describe the bug**

Migrating `@walletconnect/web3wallet` from `1.10.2` to `1.11.1` in our [project](https://github.com/dfinity/oisy-wallet) leads to following `npm run build` error:

```
x Build failed in 9.44s
x Build failed in 12.02s
error during build:
RollupError: [vite-plugin-sveltekit-compile] node_modules/@walletconnect/core/node_modules/@walletconnect/logger/dist/index.es.js (1:132): "Writable" is not exported by "__vite-browser-external", imported by "node_modules/@walletconnect/core/node_modules/@walletconnect/logger/dist/index.es.js".
file: /Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/@walletconnect/core/node_modules/@walletconnect/logger/dist/index.es.js:1:132
1: import h,{levels as i}from"pino";import{default as D}from"pino";import{safeJsonStringify as u}from"@walletconnect/safe-json";import{Writable a...
                                                                                                                                       ^
2: //# sourceMappingURL=index.es.js.map
file: /Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/@walletconnect/core/node_modules/@walletconnect/logger/dist/index.es.js:1:132
1: import h,{levels as i}from"pino";import{default as D}from"pino";import{safeJsonStringify as u}from"@walletconnect/safe-json";import{Writable a...
                                                                                                                                       ^
2: //# sourceMappingURL=index.es.js.map
    at getRollupError (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at Module.error (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/node-entry.js:13688:16)
    at Module.traceVariable (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/node-entry.js:14136:29)
    at ModuleScope.findVariable (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/node-entry.js:11817:39)
    at ChildScope.findVariable (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/node-entry.js:6037:38)
    at Identifier.bind (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/node-entry.js:7311:40)
    at ClassDeclaration.bind (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/node-entry.js:4753:23)
    at Program.bind (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/node-entry.js:4749:28)
    at Module.bindReferences (file:///Users/daviddalbusco/projects/dfinity/oisy-wallet/node_modules/rollup/dist/es/shared/node-entry.js:13669:18)
```

**To Reproduce**

Create an empty SvelteKit / Vite project and just import walletconnect `Core`.

```
<script lang="ts">
    import { Core } from '@walletconnect/core';

    console.log(Core); // <---- Reproduce the issue
</script>

<h1>Demo</h1>
```

1. git clone [https://github.com/peterpeterparker/walletconnect_1-11-1](https://github.com/peterpeterparker/walletconnect_1-11-1)
2. cd walletconnect_1-11-1
3. npm ci
4. npm run build

**Expected behavior**
No build error.

**Screenshots**

![Capture d’écran 2024-04-08 à 07 03 01](https://uploads.linear.app/53158a94-cce0-42f0-a185-428db7e671e5/d015e1b6-f9ca-4503-bf4a-f9cd9e6f481a/1d241f6f-8f36-4a57-aaf0-b285957a85e1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzMTU4YTk0LWNjZTAtNDJmMC1hMTg1LTQyOGRiN2U2NzFlNS9kMDE1ZTFiNi1mOWNhLTQ1MDMtYmY0YS1mOWNkOWU2ZjQ4MWEvMWQyNDFmNmYtOGYzNi00YTU3LWFhZjAtYjI4NTk1N2E4NWUxIiwiaWF0IjoxNzEyODkyMzg3LCJleHAiOjMzMjgzNDUyMzg3fQ.skcw_KuM2ysxTLG7woxqm8KS_N6VusyYtVboPc_or6w "=1312x")

**Comment by devceline** [comment]
Thank you for the fantastic repro case - helped expedite solve this. Fix is in this PR here and in progress https://github.com/WalletConnect/walletconnect-utils/pull/167

**Comment by peterpeterparker** [comment]
Thanks for the quick fix @devceline! I can confirm that the released patch of `@walletconnect/logger` fixes the issue in our project.
