### ISSUE TITLE
TypeError: doc.getElementsByTagName is not a function

### ISSUE THREAD

**Issue by priyeshs11** [WalletConnect/walletconnect-monorepo#511]
**Client:** `React-native`
**Library:** `"@walletconnect/client"`
**Version:** `"^1.4.1"`

**Error:**
```
[rn]  ERROR  TypeError: doc.getElementsByTagName is not a function. (In 'doc.getElementsByTagName('meta')', 'doc.getElementsByTagName' is undefined)
[rn] Error: ENOENT: no such file or directory, open '[native code]'
[rn]     at Object.openSync (fs.js:476:3)
[rn]     at Object.readFileSync (fs.js:377:35)
[rn]     at getCodeFrame (/pathToApp/node_modules/metro/src/Server.js:1296:18)
[rn]     at /pathToApp/node_modules/metro/src/Server.js:1367:24
[rn]     at Generator.next (<anonymous>)
[rn]     at asyncGeneratorStep (/pathToApp/node_modules/metro/src/Server.js:146:24)
[rn]     at _next (/pathToApp/node_modules/metro/src/Server.js:168:9)
[rn]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**The code that throws the above error:**

```
const connector = new WalletConnect({
  uri: 'wc:fefd7cdb-3b5d-4785-ba5e-e33d368f5d60@1?bridge=https%3A%2F%2Fbridge.walletconnect.org&key=e189ca05faec3a88690a1616fae7ef3376843b1d3fbea3d272ad1711d81113e1',
  clientMeta: {
    description: "WalletConnect Developer App",
    url: "https://walletconnect.org",
    icons: ["https://walletconnect.org/walletconnect-logo.svg"],
    name: "WalletConnect",
  }
);
```

**Comment by priyeshs11** [comment]
@pedrouid Could somebody please help?

**Comment by pedrouid** [comment]
Need to investigate this because I've never seen this error

Make sure you are not trying to polyfill browser window APIs because otherwise the client will believe its a browser environment instead of react-native

**Comment by finessevanes** [comment]
@priyeshs11 is this still an issue?
