### ISSUE TITLE
Issue using localhost relay server

### ISSUE THREAD

**Issue by sandeepmukh** [WalletConnect/walletconnect-monorepo#633]
I ran 
`
make dev
`
and verified that it is running on docker, but when I put the localhost uri as the bridge server connect, I get connect refused errors and 
`
make test-relay
`
also shows these errors. 

4 passing (1s)
  2 pending
  12 failing

  1) HTTP
       GET health:
     Error: connect ECONNREFUSED [IP]:5555
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)

  2) HTTP
       GET hello:
     Error: connect ECONNREFUSED [IP]:5555
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)

  3) HTTP
       POST subscribe:
     Error: connect ECONNREFUSED [IP]:5555
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16)

  4) JSON-RPC
       A can publish to B subscribed to same topic:
     Error: Unavailable WS RPC url at ws://localhost:5555
      at Object.parseConnectionError (node_modules/@walletconnect/jsonrpc-utils/src/error.ts:67:7)
      at WsConnection.parseError (node_modules/@walletconnect/jsonrpc-ws-connection/src/ws.ts:148:12)
      at WebSocket.socket.onerror (node_modules/@walletconnect/jsonrpc-ws-connection/src/ws.ts:108:28)
      at WebSocket.onError (node_modules/ws/lib/event-target.js:140:16)
      at WebSocket.emit (node:events:394:28)
      at WebSocket.emit (node:domain:475:12)
      at ClientRequest.<anonymous> (node_modules/ws/lib/websocket.js:688:15)
      at ClientRequest.emit (node:events:394:28)
      at ClientRequest.emit (node:domain:475:12)
      at Socket.socketErrorListener (node:_http_client:447:9)
      at Socket.emit (node:events:394:28)
      at Socket.emit (node:domain:475:12)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

  5) JSON-RPC
       A can publish to B and C subscribed to same topic:
     Error: Unavailable WS RPC url at ws://localhost:5555
      at Object.parseConnectionError (node_modules/@walletconnect/jsonrpc-utils/src/error.ts:67:7)
      at WsConnection.parseError (node_modules/@walletconnect/jsonrpc-ws-connection/src/ws.ts:148:12)
      at WebSocket.socket.onerror (node_modules/@walletconnect/jsonrpc-ws-connection/src/ws.ts:108:28)
      at WebSocket.onError (node_modules/ws/lib/event-target.js:140:16)
      at WebSocket.emit (node:events:394:28)
      at WebSocket.emit (node:domain:475:12)
      at ClientRequest.<anonymous> (node_modules/ws/lib/websocket.js:688:15)
      at ClientRequest.emit (node:events:394:28)
      at ClientRequest.emit (node:domain:475:12)
      at Socket.socketErrorListener (node:_http_client:447:9)
      at Socket.emit (node:events:394:28)
      at Socket.emit (node:domain:475:12)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

  6) JSON-RPC
       B can receive pending messages published while offline:
     Error: Unavailable WS RPC url at ws://localhost:5555
      at Object.parseConnectionError (node_modules/@walletconnect/jsonrpc-utils/src/error.ts:67:7)
      at WsConnection.parseError (node_modules/@walletconnect/jsonrpc-ws-connection/src/ws.ts:148:12)
      at WebSocket.socket.onerror (node_modules/@walletconnect/jsonrpc-ws-connection/src/ws.ts:108:28)
      at WebSocket.onError (node_modules/ws/lib/event-target.js:140:16)
      at WebSocket.emit (node:events:394:28)
      at WebSocket.emit (node:domain:475:12)
      at ClientRequest.<anonymous> (node_modules/ws/lib/websocket.js:688:15)
      at ClientRequest.emit (node:events:394:28)
      at ClientRequest.emit (node:domain:475:12)
      at Socket.socketErrorListener (node:_http_client:447:9)
      at Socket.emit (node:events:394:28)
      at Socket.emit (node:domain:475:12)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

  7) JSON-RPC
       A can publish to B through Provider A to Provider B:
     Error: Unavailable WS RPC url at ws://localhost:5555
      at Object.parseConnectionError (node_modules/@walletconnect/jsonrpc-utils/src/error.ts:67:7)
      at WsConnection.parseError (node_modules/@walletconnect/jsonrpc-ws-connection/src/ws.ts:148:12)
      at WebSocket.socket.onerror (node_modules/@walletconnect/jsonrpc-ws-connection/src/ws.ts:108:28)
      at WebSocket.onError (node_modules/ws/lib/event-target.js:140:16)
      at WebSocket.emit (node:events:394:28)
      at WebSocket.emit (node:domain:475:12)
      at ClientRequest.<anonymous> (node_modules/ws/lib/websocket.js:688:15)
      at ClientRequest.emit (node:events:394:28)
      at ClientRequest.emit (node:domain:475:12)
      at Socket.socketErrorListener (node:_http_client:447:9)
      at Socket.emit (node:events:394:28)
      at Socket.emit (node:domain:475:12)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

  8) JSON-RPC
       C can receive pending messages published on other providers while offline:
     Error: Unavailable WS RPC url at ws://localhost:5555
      at Object.parseConnectionError (node_modules/@walletconnect/jsonrpc-utils/src/error.ts:67:7)
      at WsConnection.parseError (node_modules/@walletconnect/jsonrpc-ws-connection/src/ws.ts:148:12)
      at WebSocket.socket.onerror (node_modules/@walletconnect/jsonrpc-ws-connection/src/ws.ts:108:28)
      at WebSocket.onError (node_modules/ws/lib/event-target.js:140:16)
      at WebSocket.emit (node:events:394:28)
      at WebSocket.emit (node:domain:475:12)
      at ClientRequest.<anonymous> (node_modules/ws/lib/websocket.js:688:15)
      at ClientRequest.emit (node:events:394:28)
      at ClientRequest.emit (node:domain:475:12)
      at Socket.socketErrorListener (node:_http_client:447:9)
      at Socket.emit (node:events:394:28)
      at Socket.emit (node:domain:475:12)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

  9) JSON-RPC
       A can publish multiple messages while B is concurrently subscribing:
     Error: Unavailable WS RPC url at ws://localhost:5555
      at Object.parseConnectionError (node_modules/@walletconnect/jsonrpc-utils/src/error.ts:67:7)
      at WsConnection.parseError (node_modules/@walletconnect/jsonrpc-ws-connection/src/ws.ts:148:12)
      at WebSocket.socket.onerror (node_modules/@walletconnect/jsonrpc-ws-connection/src/ws.ts:108:28)
      at WebSocket.onError (node_modules/ws/lib/event-target.js:140:16)
      at WebSocket.emit (node:events:394:28)
      at WebSocket.emit (node:domain:475:12)
      at ClientRequest.<anonymous> (node_modules/ws/lib/websocket.js:688:15)
      at ClientRequest.emit (node:events:394:28)
      at ClientRequest.emit (node:domain:475:12)
      at Socket.socketErrorListener (node:_http_client:447:9)
      at Socket.emit (node:events:394:28)
      at Socket.emit (node:domain:475:12)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

  10) LEGACY
       A can publish to B subscribed to same topic:
     Uncaught Error: Unhandled error. (ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'ws://localhost:5555',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'connect ECONNREFUSED [IP]5555',
  error: Error: connect ECONNREFUSED [IP]:5555
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '[IP]',
    port: 5555
  }
})
      at new NodeError (node:internal/errors:371:5)
      at EventEmitter.emit (node:events:383:17)
      at EventEmitter.emit (node:domain:475:12)
      at WebSocket.socket.onerror (test/shared/socket.ts:66:21)
      at WebSocket.onError (node_modules/ws/lib/event-target.js:140:16)
      at WebSocket.emit (node:events:394:28)
      at WebSocket.emit (node:domain:475:12)
      at ClientRequest.<anonymous> (node_modules/ws/lib/websocket.js:688:15)
      at ClientRequest.emit (node:events:394:28)
      at ClientRequest.emit (node:domain:475:12)
      at Socket.socketErrorListener (node:_http_client:447:9)
      at Socket.emit (node:events:394:28)
      at Socket.emit (node:domain:475:12)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

  11) LEGACY
       A can publish to B and C subscribed to same topic:
     Uncaught Error: Unhandled error. (ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'ws://localhost:5555',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'connect ECONNREFUSED [IP]:5555',
  error: Error: connect ECONNREFUSED [IP]:5555
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '[IP]',
    port: 5555
  }
})
      at new NodeError (node:internal/errors:371:5)
      at EventEmitter.emit (node:events:383:17)
      at EventEmitter.emit (node:domain:475:12)
      at WebSocket.socket.onerror (test/shared/socket.ts:66:21)
      at WebSocket.onError (node_modules/ws/lib/event-target.js:140:16)
      at WebSocket.emit (node:events:394:28)
      at WebSocket.emit (node:domain:475:12)
      at ClientRequest.<anonymous> (node_modules/ws/lib/websocket.js:688:15)
      at ClientRequest.emit (node:events:394:28)
      at ClientRequest.emit (node:domain:475:12)
      at Socket.socketErrorListener (node:_http_client:447:9)
      at Socket.emit (node:events:394:28)
      at Socket.emit (node:domain:475:12)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

  12) LEGACY
       B can receive pending messages published while offline:
     Uncaught Error: Unhandled error. (ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] { open: [Function], error: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'ws://localhost:5555',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'connect ECONNREFUSED [IP]:5555',
  error: Error: connect ECONNREFUSED [IP]:5555
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '[IP]',
    port: 5555
  }

**Comment by finessevanes** [comment]
Is this still an issue?
