### ISSUE TITLE
React Native: Execution failed for task ':react-native-os:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by AleeeKoi** [WalletConnect/walletconnect-monorepo#664]
Hello, I'm getting following error after running `rn-nodeify --hack --install`:

```
...\node_modules\react-native-os\android\src\main\java\com\peel\react\RNOSModule.java:31: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-os:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

    at makeError (...\node_modules\execa\index.js:174:9)
    at ...\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runOnAllDevices (...\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:106:5)
    at async Command.handleAction (...\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:192:9)
```

I'm using react-native `v0.66.1` and walletconnect `v1.6.6`.

What I'm doing wrong?
Thank you

**Comment by AleeeKoi** [comment]
There was an error with the `os` module, installing last version manually seem to work.

**Comment by mertcankose** [comment]
> There was an error with the `os` module, installing last version manually seem to work.

Can you share a repo for me? I need it a lot

**Comment by AleeeKoi** [comment]
@mertcankose I remember that I have install the nodeify components without using the automatic command cause it install an old incompatible `os` module
